{"name": "test_receive_unauthorized_user_order_list_fail", "status": "passed", "start": 1704584003749, "stop": 1704584005913, "uuid": "d42f250c-5586-487c-956c-80b2682ebd2b", "historyId": "454115947209b173caddb56bcff94811", "testCaseId": "454115947209b173caddb56bcff94811", "fullName": "tests.test_receive_user_orders.TestReceiveUserOrders#test_receive_unauthorized_user_order_list_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_receive_user_orders"}, {"name": "subSuite", "value": "TestReceiveUserOrders"}, {"name": "host", "value": "ARSENIY-PC"}, {"name": "thread", "value": "15820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_receive_user_orders"}]}